### ISSUE TITLE
Add MailHog  for email testing 

### ISSUE THREAD

**Issue by tugrulpinar** [stribny/sidewinder#23]
Hey @stribny I love your work here. I think adding an email testing tool for developers would be a great addition.

If you wish I can contribute this snippet inside the `docker-compose.yml`

```yml
  mailhog: 
    image: mailhog/mailhog:latest 
    restart: always 
    ports: 
      -1025:1025 
      -8025:8025 
```
