### ISSUE TITLE
Add Ruff as Python linter and code formatter

### ISSUE THREAD

**Issue by tugrulpinar** [stribny/sidewinder#24]
[Ruff](https://docs.astral.sh/ruff/) is an extremely fast Python linter and code formatter, written in Rust. ⚡ 
Drop-in parity with [Flake8](https://docs.astral.sh/ruff/faq/#how-does-ruff-compare-to-flake8), isort, and Black

The `pre-commit-config.yml` file would look like below:

```yml
# Run the Ruff formatter.
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.291
  hooks:
    - id: ruff-format
# Run the Ruff linter.
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.291
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
```

Also there would be no need for `.flake8`, `.isort.cfg`.
Ruff can replace `black`, `isort`, and `black` as a dependency.
